# Generated by Django 5.1.6 on 2025-02-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0003_remove_customer_fullname_remove_customer_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$YAOZvdF0RDzWsN9HSqchVK$JJ6puJ5qmHlXF8a+8OcklbTTBmuRBvqywtaewgVHn/8=",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(default="user123", max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
