# Generated by Django 5.1.6 on 2025-02-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0004_remove_customer_name_remove_customer_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$hCYF4ehQ3YXC0gFxK41Yg5$tgbuYt0eGVNKNgY5DBj5gMwoYcjvR+mkHJhl5NNzO6Y=",
                max_length=255,
            ),
        ),
    ]
