# Generated by Django 5.1.6 on 2025-02-15 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "Accounts",
            "0006_remove_customer_first_name_remove_customer_last_name_and_more",
        ),
        ("Cart", "0007_alter_order_customer_alter_shoppingaddress_customer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
