# Generated by Django 5.1.6 on 2025-02-13 09:14

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=Products.models.get_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
