# Generated by Django 5.1.6 on 2025-02-13 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0002_alter_product_description_alter_product_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
    ]
