# Generated by Django 5.1.6 on 2025-02-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0003_remove_product_created_at_remove_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="category", max_length=200, unique=True),
        ),
    ]
