# Generated by Django 5.1.6 on 2025-02-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0004_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
