# Generated by Django 5.1.6 on 2025-02-16 05:08

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0005_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="collection",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_image1",
            field=models.ImageField(
                blank=True,
                default="icon/default-product.jpg",
                null=True,
                upload_to=Products.models.get_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_image2",
            field=models.ImageField(
                blank=True,
                default="icon/default-product.jpg",
                null=True,
                upload_to=Products.models.get_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_image3",
            field=models.ImageField(
                blank=True,
                default="icon/default-product.jpg",
                null=True,
                upload_to=Products.models.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="icon/default-product.jpg",
                null=True,
                upload_to=Products.models.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
    ]
