# Generated by Django 5.1.6 on 2025-02-16 14:37

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0006_remove_product_stock_product_collection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="icon/default-product.jpg",
                max_length=255,
                null=True,
                upload_to=Products.models.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_image1",
            field=models.ImageField(
                blank=True,
                default="icon/default-product.jpg",
                max_length=255,
                null=True,
                upload_to=Products.models.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_image2",
            field=models.ImageField(
                blank=True,
                default="icon/default-product.jpg",
                max_length=255,
                null=True,
                upload_to=Products.models.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_image3",
            field=models.ImageField(
                blank=True,
                default="icon/default-product.jpg",
                max_length=255,
                null=True,
                upload_to=Products.models.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.FloatField(help_text="Trọng lượng kim cương(carat)"),
        ),
    ]
