services:
 db:
   image: mysql:latest
   restart: always
   ports:
     - "3307:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=123123
     - MYSQL_DATABASE=Administrator

 adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"