# Generated by Django 5.1.6 on 2025-02-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_remove_customer_address_remove_customer_phonenumber"),
        ("Cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200, null=True)),
                ("phonenumber", models.CharField(max_length=12, null=True)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Cart.order"
                    ),
                ),
            ],
        ),
    ]
