# Generated by Django 5.1.6 on 2025-02-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0004_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
