# Generated by Django 5.1.6 on 2025-02-13 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0005_alter_orderitem_price"),
        ("Products", "0003_remove_product_created_at_remove_product_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="shoppingaddress",
            name="date_add",
        ),
        migrations.AddField(
            model_name="order",
            name="complete",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Cart.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
